### ISSUE TITLE
How to install your repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [kai3316/YOLIC-Labeling#14]
Hi,
I want to use your repo for some testing.  I am using Visual Studio 2022, version 17.10.3; I did the following: 
D:\> git clone Url of your repo.
Then open the repo using both Visual Studio 2019 & 2022; but the both Visual Studion

..\Installer\Installer.vdproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660952&projecttype=54435603-DBB4-11D2-8724-00A0C9A8B90C

Let me know how can I install your repo, and what kind of job this repo can do?
Thanks,
![InstallYOLCNOK](https://github.com/kai3316/YOLIC-Labeling/assets/45263518/a5e24055-85d7-408e-b700-9658f7a92ced)

**Comment by zydjohnHotmail** [comment]
By the way, I am using Window 10 version 22H2.
What environment you used to develop this repo?
Best Regards,

**Comment by kai3316** [comment]
Hi,
Thank you for your interest in using this tool for testing!
This error occurs when the Visual Studio Installer Projects extension is not installed in your Visual Studio environment. I have removed the installer configuration project from the source code to resolve this issue.

To install the software, please follow these steps:

1. Go to the "Releases" section of the repository.
2. Download the `Tool.msi` file, which is a pre-compiled installer.
3. Run the `Tool.msi` file on your Windows machine to install this annotation tool.

For detailed information on how to use the software and its various features, please refer to the `Usage.pdf` file included in the repository.
Best Regards,
Kai

**Comment by zydjohnHotmail** [comment]
Hi,
I can install your repo. Thanks for your help. But when I run it, I found it a kind of complicated, do you have some documents, better with a few screenshots so I know how to use it.  Or I can show you one image, give me some instructions on how to use your repo on this image, I am intested to know how to read those numbers, like: 1, 2, 3, 4, 5, 6, 7.  I want to know esp. about number 2, take a look at the image.
![first_frame](https://github.com/kai3316/YOLIC-Labeling/assets/45263518/8516cc5d-1d70-4e43-aa10-c98de01bf768)

Thanks,

**Comment by kai3316** [comment]
Thank you for reaching out and letting me know that you were able to successfully install the repository.  Please look at the Usage.pdf file in the repository for detailed information. It's important to note that this tool is primarily designed for annotating images to train YOLIC models, rather than directly recognizing numbers or other objects in images. The tool itself does not have the capability to identify the numbers like 1, 2, 3, 4, 5, 6, 7 that you mentioned in your image.

If your goal is to train a YOLIC model to recognize numbers at specific locations in an image, here's what you need to do:

1. Configure the cell configuration file to define the numbers you want to recognize and their corresponding locations in the image.

2. Use the YOLIC Labeling Tool to annotate a set of images, labeling the numbers at their respective locations as defined in the configuration file.

3. Once you have annotated a sufficient number of images, use the generated annotation files along with the corresponding images to train your YOLIC model.

The trained model will then be able to recognize the numbers at the specified locations in new, unseen images. Refer to the project's [code](https://github.com/kai3316/YOLIC_code) to train a YOLIC detection model. For more information on the YOLIC method, please refer to the paper "YOLIC: An Efficient Method for Object Localization and Classification on Edge Devices"
